Repository depromeet/Ding-dong-BE, pull requests merged in 2023-05, with the labels that each got.

#2 DEP-26: 코드 포맷팅 정리
  Api/src/main/java/com/demo/api/config/GlobalExceptionHandler.java
  Api/src/main/java/com/demo/api/config/SuccessResponseAdvice.java
  Api/src/main/java/com/demo/api/config/SwaggerConfig.java
  Api/src/main/java/com/demo/api/config/security/AccessDeniedFilter.java
  Api/src/main/java/com/demo/api/config/security/CorsConfig.java
  Api/src/main/java/com/demo/api/config/security/CustomUserDetails.java
  Api/src/main/java/com/demo/api/config/security/JwtTokenFilter.java
  Api/src/main/java/com/demo/api/config/security/SecurityConfig.java
  Api/src/main/java/com/demo/api/config/security/SecurityUtils.java
  Api/src/main/java/com/demo/api/example/HealthCheckController.java
  Core/src/main/java/com/demo/core/annotation/Adaptor.java
  Core/src/main/java/com/demo/core/annotation/DomainService.java
  Core/src/main/java/com/demo/core/annotation/Helper.java
  Core/src/main/java/com/demo/core/annotation/UseCase.java
  Core/src/main/java/com/demo/core/annotation/Validator.java
  Core/src/main/java/com/demo/core/config/ConfigurationPropertiesConfig.java
  Core/src/main/java/com/demo/core/consts/StaticVal.java
  Core/src/main/java/com/demo/core/exception/BaseErrorCode.java
  Core/src/main/java/com/demo/core/exception/BaseException.java
  Core/src/main/java/com/demo/core/jwt/JwtTokenProvider.java
  Domain/src/main/java/com/demo/domain/config/QueryDslConfig.java
  Domain/src/main/java/com/demo/domain/domains/AbstractTimeStamp.java
  Infrastructure/src/main/java/com/demo/infrastructure/config/redis/RedisCacheConfig.java
  Infrastructure/src/main/java/com/demo/infrastructure/config/redis/RedisConfig.java
  Infrastructure/src/main/java/com/demo/infrastructure/config/redis/RedissonConfig.java
Labels: Type: Refactor

#4 DEP-23: 인프라 구성(CI/CD)
  .github/workflows/deploy.yml
  Dockerfile
  Infrastructure/src/main/resources/application-infrastructure.yml
  docker-compose.yml
Labels: For: Deploy

#6 style: spotless 적용
  Api/src/main/java/com/dingdong/api/config/GlobalExceptionHandler.java
  Api/src/main/java/com/dingdong/api/config/SuccessResponseAdvice.java
  Api/src/main/java/com/dingdong/api/config/SwaggerConfig.java
  Api/src/main/java/com/dingdong/api/config/security/AccessDeniedFilter.java
  Api/src/main/java/com/dingdong/api/config/security/CorsConfig.java
  Api/src/main/java/com/dingdong/api/config/security/CustomUserDetails.java
  Api/src/main/java/com/dingdong/api/config/security/JwtTokenFilter.java
  Api/src/main/java/com/dingdong/api/config/security/SecurityConfig.java
  Api/src/main/java/com/dingdong/api/config/security/SecurityUtils.java
  Api/src/main/java/com/dingdong/api/example/HealthCheckController.java
  Core/src/main/java/com/dingdong/core/annotation/Adaptor.java
  Core/src/main/java/com/dingdong/core/annotation/DomainService.java
  Core/src/main/java/com/dingdong/core/annotation/Helper.java
  Core/src/main/java/com/dingdong/core/annotation/UseCase.java
  Core/src/main/java/com/dingdong/core/annotation/Validator.java
  Core/src/main/java/com/dingdong/core/config/ConfigurationPropertiesConfig.java
  Core/src/main/java/com/dingdong/core/consts/StaticVal.java
  Core/src/main/java/com/dingdong/core/exception/BaseErrorCode.java
  Core/src/main/java/com/dingdong/core/exception/BaseException.java
  Core/src/main/java/com/dingdong/core/jwt/JwtTokenProvider.java
  Domain/src/main/java/com/dingdong/domain/config/QueryDslConfig.java
  Domain/src/main/java/com/dingdong/domain/domains/AbstractTimeStamp.java
  Infrastructure/src/main/java/com/dingdong/infrastructure/config/redis/RedisCacheConfig.java
  Infrastructure/src/main/java/com/dingdong/infrastructure/config/redis/RedisConfig.java
  Infrastructure/src/main/java/com/dingdong/infrastructure/config/redis/RedissonConfig.java
Labels: Type: Docs/Chore

#7 DEP-28 에러로깅 센트리 연동
  Api/build.gradle
  Api/src/main/java/com/dingdong/api/example/HealthCheckController.java
  Api/src/main/resources/application.yml
  Api/src/main/resources/logback-spring.xml
Labels: Type: Feature

#8 DEP-23: 인프라 구성(CI/CD)
  .github/workflows/build.yml
  .github/workflows/deploy.yml
Labels: For: Deploy
